.travis.yml, R/translate.R
Fix #1 
[Named capture groups](http://site.icu-project.org/design/regular-expressions/named-capture-groups) feature is available only after ICU 55, but this newer ICU is not always available. So, it seems better to remove them at least for now.
=> Remove named capture groups

DESCRIPTION, NEWS.md, R/util.R
(Related to #10)
Currently, conflr uses `rstudioapi::showPrompt()` and `rstudioapi::askForPassword()`. But, these are not available outside RStudio. This PR changes the method to askpass package, which works well in many cases. askpass package is licensed under MIT, so adding this doesn't conflict with the current packages.
c.f. https://github.com/jeroen/askpass
Note that, conflr stilll uses `showPrompt()` if possible, since it's slightly more convenient in that we can set the default value on it.
=> Use askpass to enable to ask URL, username, and password outside RStudio

NEWS.md, R/addin.R, R/content.R, R/translate.R, man/confl_content.Rd, tests/testthat/test-translate.R
Fix #21 
Currently, conflr sets the *height* to 400 on all images that don't have *height* attribute; if an image has its own heights and width, those are respected by the change of #7.
This PR changes to set *width* to 600 on on all images that don't have *width* attribute. Probably, this changes the visual appearance, but setting width is in line with what the Confluence's editor does.
This PR adds a new argument `image_size_default` to `confl_post_page()` and `confl_update_page()`. When this is `NULL`, no `width` or `height` will be set, which means the images will be displayed as the original sizes.
But the parameter is not directly exposed to the addin. Instead, a simple checkbox is added for simplicity. If this is checked, `image_size_default = NULL` is used.
* Update README in …
=> Add an option to control the default size of the image

NEWS.md, R/addin.R, R/content.R, man/confl_content.Rd, tests/testthat/test-content.R
Fix #20 
Add `minor_edit` option to `confl_update_page()`. For addin, "Notify watchers" (the same label as the Confluence's editor) option is added.
=> Add an option to control whether to notify watchers or not

R/addin.R, R/content.R, man/confl_content.Rd, tests/testthat/test-content.R
`minorEdit` option doesn't seem to work. Revert for now to avoid confusion.
See #20 for the details.
=> Revert #23

R/addin.R, R/console.R, man/confl_create_post_from_Rmd.Rd
Hello again!
I was wanting to automate a page upload to confluence, but the current setup page upload flow requires going through the shiny app. In order to enable scriptable uploading I made a few changes:
1) Added `confl_console_upload()` in `console.R` that is essentially just the server-side code from the shiny app on its own. I made the options in the Shiny app into function arguments. Also, the function returns the url of the published page for further scripting (e.g. notification to others).
2) Added a `shiny` argument to `confl_create_post_from_Rmd()` that when set to `FALSE` uses the new console upload function for publishing instead of `confl_addin_upload()`. Also added `...` to pass the needed arguments down to the console upload function.
3) Added an optional `title` argument …
=> Console Upload

R/addin.R, man/confl_create_post_from_Rmd.Rd
Fix this error: https://stackoverflow.com/questions/57068756/cant-publish-r-mardown-to-confluence-using-conflr
(Not sure about the detail, but it seems we should avoid using `interactive()` as the default argument)
=> Do not use interactive() as the default argument

R/addin.R
(Fix #29)
According to https://github.com/Rdatatable/data.table/blob/5ceda0f383f91b7503d4a236ee4e7438724340be/R/cedta.R#L4-L20, I have two choice to fix this problem:
1. Specify `assignInNamespace("cedta.pkgEvalsUserCode", c(data.table:::cedta.pkgEvalsUserCode,"<nsname>"), "data.table")` to tell data.table to aware of conflr (?)
2. Specify the knit environment as the global environment, where data.table is supposed to work fine.
Not fully understand the problem, but this PR chose the option 2 because I want to avoid introducing package-dependent codes. I hope this change won't cause any harm...
=> Specify the knit environment as global

NEWS.md, R/translate.R, tests/testthat/test-translate.R
If the `src` of a `<img>` tag is external, conflr should nothing on it, because Confluence will handle it. Currently, it's mistranslated as below, which is a clear mistake...
``` xml
<ac:image ac:width="600"><ri:attachment ri:filename="..." /></ac:image>
```
=> Do not translate external image to Conflence macro

NEWS.md, R/util.R, README.Rmd, README.md, tests/testthat/test-utils.R
Close #42 (for the details, see the discussion on #41)
Users are now able to choose not to cache the input in the envvars by setting this option:
``` r
options(conflr_dont_cache_envvar = TRUE)
```
=> Add an option not to chace the URL username and password as envvars

R/addin.R
This PR is to add the ability to write post-settings on Rmd's yaml-front-matter.
Example is here:
```yaml
---
title: "conflr post test"
confl_setting:
tags: "hoge"
space_key: "my_space"
parent_id: "123456789"
type: "page"
update: TRUE
use_original_size: FALSE
---
```
=> Add the ability to write post-settings on Rmd

R/addin.R
There is a bug on `use_original_size` using `confl_create_post_from_Rmd()` with `interactive = FALSE`.
This PR is to fix it.
=> fix a bug on use_original_size

NEWS.md, R/addin-internals.R, R/addin.R, man/confl_create_post_from_Rmd.Rd, tests/testthat/helpers.R, tests/testthat/test-front-matter.R, tests/testthat/test-toc.R
Close #64 
`toc` can be set via front-matter
``` md
---
title: title1
confluence_settings:
space_key: space1
toc: true
---
```
or via argument of `confl_create_post_from_Rmd()`.
``` r
confl_create_post_from_Rmd(Rmd_file, interactive = FALSE, update = TRUE, toc = TRUE)
```
=> Support TOC

NEWS.md, R/addin-internals.R, R/addin.R, man/confl_create_post_from_Rmd.Rd, tests/testthat/test-front-matter.R, tests/testthat/test-toc.R
Fix #67 
The `toc_depth` can be specified via `maxLevel` parameter whose default is `7` c.f. https://confluence.atlassian.com/doc/table-of-contents-macro-182682099.html
=> Support toc_depth

R/addin-internals.R, R/addin.R, R/translate.R, man/confl_create_post_from_Rmd.Rd, tests/testthat/test-front-matter.R, tests/testthat/test-translate.R
Fix #54 
The implementation is almost done in #55. This PR exposes the parameter to users. `supported_syntax_highlighting` can be set either via a parameter of front-matter, 
``` yaml
title: "title1"
confluence_settings:
space_key: "space1"
supported_syntax_highlighting:
- r
```
or via an argument,
``` r
confl_create_post_from_Rmd(
Rmd_file, interactive = FALSE, update = TRUE,
supported_syntax_highlighting = "r"
)
```
or via an option.
``` r
options(conflr_supported_syntax_highlighting = "r")
```
=> Expose supported_syntax_highlighting

NEWS.md, R/addin-internals.R, R/addin.R, R/content.R, R/translate.R, man/confl_content.Rd, man/confl_create_post_from_Rmd.Rd, tests/testthat/test-toc.R, tests/testthat/test-translate.R
Fix #65 
* Replace `ac:` namespace with `confl-ac-` so that it can avoid getting escaped by `commonmark::markdown_html()`
* To make the implementation simple, do `translate_to_confl_macro()` outside of `confl_(update|post)_page()`.
=> Bypass conversion of <ac:...> and <ri:...>

R/addin.R, R/document.R
Currently the options are not set if the user doesn't use addin. This PR fixes the inconsistency by moving the logic into the custom format.
=> Set opts_chunk in confluence_document() for consistency

R/addin-internals.R, R/addin.R, R/document.R
Fix #95
After #77, uploading is done inside the `post_processor` of a custom R Markdown document, which can return only `output_file`. So, it's a bit hard to propagate the information to the caller. Possible choices are
1. environment
2. file
and I chose option 2 since environment might not be very safe with the previous results.
Note that, at the moment the file only contains the URL, but probably we can put the whole response from the Confluence into the file. Let's consider when it's needed.
=> Make confl_create_post_from_Rmd() return the result URL

R/addin-internals.R, R/addin.R, R/content.R, R/document.R, man/confl_content.Rd, man/confluence_document.Rd, tests/testthat/test-content.R
This adds back the reverted feature from #25 -- as it seems to work really nicely with the page update calls.
=> add option to mark page updates as minor edit

R/addin-internals.R, R/attachment.R, man/confl_attachment.Rd
Followup of #107, which hopefully closes #20  
Add `minor_edit` option to the following functions, and pass it inside `confl_upload()`:
* `confl_post_attachment()`
* `confl_update_attachment()`
=> Propagate minor_edit to attatchment operations

NEWS.md, R/addin.R, R/document.R, R/tabset.R, R/translate.R, tests/testthat/test-tabset.R
Close #82 
rmarkdown package implements tabset feature mostly on JavaScript's side, so imitating it on Confluence is a very tough job.
`{.tabset}` notation is only available on Pandoc markdown and will be blown away when it gets converted to commonmark. So, we need to tweak it before executing `pandoc`. This should be done in `pre_processor()`. This PR replaces `{.tabset}` with `<tabset-start/>` tags so that we can handle this as an XML a bit easier on the next step.
Keep in mind that this risks to mess the text files because of the encoding problems. If there's no tabsets, we shouldn't do anything.
This is done in `translate_to_confl_macro()` as usual. We need to see the order of header tags to determine the end of the tabset section. Take a look at some examples. 
In this example, there …
=> Support tabset

README.Rmd
Hi, I noticed a small typo in the readme, `conflr::confluence_document` was misspelled. I only modified the R Markdown file, the knitted .md file still needs to be rendered.
=> small typo in readme

R/macros.R
I hit some strange XML read parsing errors ... that I was not able to trace back properly, but spending a couple hours (duh) on this, it seems that separating the `ac` tags on their own line fixes the issue :thinking: 
I suspected it might be due to some regular expression tweaks that is now not causing the issues due to the split lines, but I was not able to debug any further.
Anyway, this fixes the issues with the complex macro blocks ... so I thought it would make sense to contribute back to the main repo, and you might also know better why this extra whitespace is needed :shrug:
=> add whitespace
